#
# Default language
#
lang: en

#
# This title will be shown on top of the menu if no logo image is specified.
# It's possible to specify a single string for all languages or to configure
# each language separately. Use 'default' as a language code to have
# a default fallback title.
#
title:
  en: Math to Touch
  es: Matemática para tocar
  ru: Математика на ощупь
  ro: Matematica de atins
  it: Math to Touch
  pt-br: Matemática para tocar

#
# Logo image to show on top of the menu.
# It's possible to specify a single image file or to configure each language
# separately. If separate languages are used then any languages without an
# image will use the title instead. Use 'default' as a language code to have
# a default fallback logo image.
#
# example: Single image for all languages:
#
# logo: assets/img/lg_imaginary_white.png
#
# example: Only use logo for english and german
#
# logo:
#   en: assets/img/lg_imaginary_white.png
#   de: assets/img/lg_imaginary_white.png

#
# Plug-ins to load
#
# plugins:
#  - plugins/my-plugin

#
# Name of the theme to use.
# Available themes: default, blue, green.
# See more info about defining new themes in the README.md file.
#
# theme: blue

#
# List of apps to load in the menu
# Each app is specified by the path or URL to the app directory where the
# app.json manifest file is located. See the README.md file for information
# on the app.json file format.
#
apps:
  - https://imaginary.github.io/cindyjs-apps/euclidian-rhythm
  - https://imaginary.github.io/cindyjs-apps/mozart-dice
  - https://imaginary.github.io/cindyjs-apps/pachelbel-canon
  - https://imaginary.github.io/cindyjs-apps/sequenzer
  - https://imaginary.github.io/cindyjs-apps/whitney
  - https://imaginary.github.io/cindyjs-apps/iornament
  - https://imaginary.github.io/cindyjs-apps/doppelpendel
  - https://imaginary.github.io/cindyjs-apps/fish
  - https://imaginary.github.io/cindyjs-apps/sphere-chaos
  - https://imaginary.github.io/cindyjs-apps/ausparken
  - https://imaginary.github.io/cindyjs-apps/kaleidoskop
  - https://imaginary.github.io/cindyjs-apps/platonic-solids
  - https://imaginary.github.io/cindyjs-apps/polytope-morpher
  - https://imaginary.github.io/cindyjs-apps/solitaire
  - https://imaginary.github.io/cindyjs-apps/image-spiral
  - https://imaginary.github.io/cindyjs-apps/tree

#
# App to load when the user clicks on the "info" button. Typically an
# "about" or "credits" app.
#
infoApp: https://imaginary.github.io/cindyjs-apps/info

#
# Text that will be shown in the menu beneath the app icons.
# It's possible to specify a single string for all languages or to configure
# each language separately. Use 'default' as a language code to have
# a default fallback title.
#
# infoText:
#  en: Help text
#  es: Texto de ayuda

#
# Icons per row
# Allows overriding the default icon layout by specifying an array of integers
# indicating how many icons to use per row.
# This new layout will only be used if the sum of all rows matches exactly the
# number of apps, and if no row exceeds the maximum number of icons allowed (6).
#
# iconsPerRow: [3, 5, 6]


#
# Max icons per row
# Maximum number of icons per row. If you change the default you might need to
# do CSS tweaking (possibly major) to maintain correct rendering with variable
# numbers of icons.
# (default: 6)
# maxIconsPerRow: 6

#
# Show language switcher menu (true/false)
#
# NOTE: It's not always a good idea to enable a language switcher. It will make
# it more difficult for people coming across the station and people watching over
# the user's shoulder to understand what's going on and they might just walk
# away or waste time finding how to switch languages instead of playing with our
# software. Enable ONLY if needed for the exhibition.
#
# IMPORTANT: If you enable the language menu choose which languages to show
# wisely! Select only those appropriate to the exhibition and avoid showing
# more than one local variant of the same language.
# Also only enable languages for which translations are available.
#
langMenuShow: true

#
# Indicate which languages to show if the language switcher menu is shown
# (use ISO 639-1 language codes)
#
langMenuItems:
  - en
  - de
  - es
  - it
  - pt-br
  - ro
  - ru
  - zh
