lang: en
title:
  en: Math to Touch
  es: Matemática para tocar
logo:
  lg: assets/img/lg_imaginary_white.png
apps:
  - apps/cindyjs/iornament
  - apps/cindyjs/doppelpendel
  - apps/cindyjs/fish
  - apps/cindyjs/sphere-chaos
  - apps/cindyjs/ausparken
  - apps/cindyjs/kaleidoskop
  - apps/cindyjs/platonic-solids
  - apps/cindyjs/polytope-morpher
  - apps/cindyjs/solitaire
  - apps/cindyjs/image-spiral
  - apps/cindyjs/tree
infoApp: apps/cindyjs/info